// models/scan_history.dart

import 'package:hive/hive.dart';

part 'scan_history.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 0) // typeId must be unique for each HiveObject
class ScanHistory extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String imagePath;

  @HiveField(2)
  final String classificationResult;

  @HiveField(3)
  final String rubbishName;

  @HiveField(4)
  final int price;

  @HiveField(5)
  final DateTime timestamp;

  ScanHistory({
    required this.id,
    required this.imagePath,
    required this.classificationResult,
    required this.rubbishName,
    required this.price,
    required this.timestamp,
  });

  // These methods are still useful and can be kept.
  ScanHistory copyWith({
    String? id,
    String? imagePath,
    String? classificationResult,
    String? rubbishName,
    int? price,
    DateTime? timestamp,
  }) {
    return ScanHistory(
      id: id ?? this.id,
      imagePath: imagePath ?? this.imagePath,
      classificationResult: classificationResult ?? this.classificationResult,
      rubbishName: rubbishName ?? this.rubbishName,
      price: price ?? this.price,
      timestamp: timestamp ?? this.timestamp,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is ScanHistory && other.id == id;
  }

  @override
  int get hashCode {
    return id.hashCode;
  }

  @override
  String toString() {
    return 'ScanHistory(id: $id, imagePath: $imagePath, classificationResult: $classificationResult, rubbishName: $rubbishName, price: $price, timestamp: $timestamp)';
  }
}
